# fly.toml app configuration file generated for archon-1 on 2025-04-23T23:38:43Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'archon-1'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
